'    Rod of Wonder Dice Roller

'    Copyright (c)  2023 by Gary J. Teixeira Jr.
'    Permission is granted to copy. distribute and/or modify this program
'    under the terms of the Attribution-NonCommercial 4.0 International License

'    This program is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

'    You may contact the developer at: ambientmine@protonmail.com


' Change ° to degrees
' Change % to percent
' Test Double Quotes (")
' Fix About Box

VERSION 5.00
Begin VB.Form Form1 
   Caption         =   "Rod Of Wonder Dice Roller"
   ClientHeight    =   2160
   ClientLeft      =   60
   ClientTop       =   390
   ClientWidth     =   13845
   LinkTopic       =   "Form1"
   ScaleHeight     =   2160
   ScaleWidth      =   13845
   StartUpPosition =   2  'CenterScreen
   Begin VB.CommandButton Command1 
      Caption         =   "ROLL!"
      CausesValidation=   0   'False
      BeginProperty Font 
         Name            =   "Times New Roman"
         Size            =   24
         Charset         =   0
         Weight          =   700
         Underline       =   0   'False
         Italic          =   0   'False
         Strikethrough   =   0   'False
      EndProperty
      Height          =   1095
      Left            =   4680
      TabIndex        =   1
      Top             =   120
      Width           =   4695
   End
   Begin VB.TextBox Text1 
      BeginProperty Font 
         Name            =   "Times New Roman"
         Size            =   12
         Charset         =   0
         Weight          =   400
         Underline       =   0   'False
         Italic          =   0   'False
         Strikethrough   =   0   'False
      EndProperty
      Height          =   495
      Left            =   0
      TabIndex        =   0
      Text            =   "Text1"
      Top             =   1440
      Width           =   13815
   End
   Begin VB.Label Label1 
      Caption         =   "Label1"
      Height          =   375
      Left            =   360
      TabIndex        =   2
      Top             =   120
      Visible         =   0   'False
      Width           =   855
   End
End
Attribute VB_Name = "Form1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Private Sub Command1_Click()
    '// Initializes the random-number generator, otherwise each time you run your
    '// program, the sequence of numbers will be the same
    Option Explicit
    DefLng A-Z
    Randomize 
    Label1.Caption = & Format(RandomNumBetween(1, 10000))
    If (Label1.Caption = 1) Then
        Text1.Text = "1d10 of caster’s fingers turn to stone"
    ElseIf (Label1.Caption = 2) Then
        Text1.Text = "1d100 bees swarm harmlessly around the caster for several weeks"
    ElseIf (Label1.Caption = 3) Then
        Text1.Text = "1d100 sparkling motes dance about the caster’s head until dawn"
    ElseIf (Label1.Caption = 4) Then
        Text1.Text = "1d100% of caster’s body turns to iron for that many rounds"
    ElseIf (Label1.Caption = 5) Then
        Text1.Text = "1d12 ducklings identify the caster as their mother"
    ElseIf (Label1.Caption = 6) Then
        Text1.Text = "1d4 of caster’s fingers move from his left hand to his right hand"
    ElseIf (Label1.Caption = 7) Then
        Text1.Text = "1d4 of caster’s limbs are as durable as steel"
    ElseIf (Label1.Caption = 8) Then
        Text1.Text = "1d4 of caster’s limbs are covered in fish scales"
    ElseIf (Label1.Caption = 9) Then
        Text1.Text = "1d4 of caster’s limbs are invisible"
    ElseIf (Label1.Caption = 10) Then
        Text1.Text = "1d8 of caster’s primary orifices seal shut"
    ElseIf (Label1.Caption = 11) Then
        Text1.Text = "3d10 harmless lumps as big as walnuts cover the caster’s body"
    ElseIf (Label1.Caption = 12) Then
        Text1.Text = "3d10 quarts of olive oil pour from caster’s ears"
    ElseIf (Label1.Caption = 13) Then
        Text1.Text = "4d6 non-functioning eyes appear on the caster’s face and head"
    ElseIf (Label1.Caption = 14) Then
        Text1.Text = "A 100 yard radius around caster’s home is stripped of vegetation"
    ElseIf (Label1.Caption = 15) Then
        Text1.Text = "A 2d6 foot radius around caster sinks as many feet into the earth"
    ElseIf (Label1.Caption = 16) Then
        Text1.Text = "A basement’s been installed in caster’s home while he’s been away"
    ElseIf (Label1.Caption = 17) Then
        Text1.Text = "A close friend of the caster is an assassin hired to kill him"
    ElseIf (Label1.Caption = 18) Then
        Text1.Text = "A distant but powerful army declares war on the caster"
    ElseIf (Label1.Caption = 19) Then
        Text1.Text = "A drop of the caster’s blood can purify 1d4 gallons of water"
    ElseIf (Label1.Caption = 20) Then
        Text1.Text = "A family of skunks has taken up residence in the caster’s home"
    ElseIf (Label1.Caption = 21) Then
        Text1.Text = "A fast-growing oak sprouts beneath the caster’s home"
    ElseIf (Label1.Caption = 22) Then
        Text1.Text = "A foot-long steel bar runs completely through the caster’s thigh"
    ElseIf (Label1.Caption = 23) Then
        Text1.Text = "A geyser temporarily erupts from one of the caster’s pockets"
    ElseIf (Label1.Caption = 24) Then
        Text1.Text = "A glowing orb hovers over caster’s head while he’s invisible"
    ElseIf (Label1.Caption = 25) Then
        Text1.Text = "A great wind blows the caster 1d100 yards in a random direction"
    ElseIf (Label1.Caption = 26) Then
        Text1.Text = "A group of necromancers take an interest in the caster’s skeleton"
    ElseIf (Label1.Caption = 27) Then
        Text1.Text = "A group of scholars think the caster’s a visitor from the future"
    ElseIf (Label1.Caption = 28) Then
        Text1.Text = "A hen’s egg tumbles out of each of the caster’s ears"
    ElseIf (Label1.Caption = 29) Then
        Text1.Text = "A huge balloon shaped like the caster drifts past overhead"
    ElseIf (Label1.Caption = 30) Then
        Text1.Text = "A kill-on-sight order has been issued for the caster kingdom-wide"
    ElseIf (Label1.Caption = 31) Then
        Text1.Text = "A large haystack falls from the sky onto caster"
    ElseIf (Label1.Caption = 32) Then
        Text1.Text = "A large oak sprouts from one of the caster’s pockets"
    ElseIf (Label1.Caption = 33) Then
        Text1.Text = "A length of chain now runs completely through the caster’s torso"
    ElseIf (Label1.Caption = 34) Then
        Text1.Text = "A life-sized statue of caster appears nearby, made of cheese"
    ElseIf (Label1.Caption = 35) Then
        Text1.Text = "A magical blast detonates at caster’s location, but he’s unharmed"
    ElseIf (Label1.Caption = 36) Then
        Text1.Text = "A mound of snow falls onto caster and buries him up to his chest"
    ElseIf (Label1.Caption = 37) Then
        Text1.Text = "A page falls out of caster’s spellbook each time it’s opened"
    ElseIf (Label1.Caption = 38) Then
        Text1.Text = "A skeleton mimics caster, exactly duplicating his movements"
    ElseIf (Label1.Caption = 39) Then
        Text1.Text = "A small fountain wells up in the caster’s home"
    ElseIf (Label1.Caption = 40) Then
        Text1.Text = "A strong net falls from the sky and entangles the caster"
    ElseIf (Label1.Caption = 41) Then
        Text1.Text = "A swirl of rainbows accompanies any spell cast by caster"
    ElseIf (Label1.Caption = 42) Then
        Text1.Text = "A tornado picks caster up and deposits him atop the nearest house"
    ElseIf (Label1.Caption = 43) Then
        Text1.Text = "After a horrifying tragedy, caster squanders the world’s goodwill"
    ElseIf (Label1.Caption = 44) Then
        Text1.Text = "After each spell, a lighted cigar appears in caster’s mouth"
    ElseIf (Label1.Caption = 45) Then
        Text1.Text = "After each spell, a pebble falls from each of caster’s ears"
    ElseIf (Label1.Caption = 46) Then
        Text1.Text = "After each spell, ants seem to course from the caster’s eyes"
    ElseIf (Label1.Caption = 47) Then
        Text1.Text = "After each spell, caster accuses someone nearby of impropriety"
    ElseIf (Label1.Caption = 48) Then
        Text1.Text = "After each spell, caster appears astonishingly ugly for 1d4 turns"
    ElseIf (Label1.Caption = 49) Then
        Text1.Text = "After each spell, caster appears to be decomposing"
    ElseIf (Label1.Caption = 50) Then
        Text1.Text = "After each spell, caster appears to be made of pure ice"
    ElseIf (Label1.Caption = 51) Then
        Text1.Text = "After each spell, caster appears to be utterly insane"
    ElseIf (Label1.Caption = 52) Then
        Text1.Text = "After each spell, caster applauds himself"
    ElseIf (Label1.Caption = 53) Then
        Text1.Text = "After each spell, caster begs someone nearby not to kill him"
    ElseIf (Label1.Caption = 54) Then
        Text1.Text = "After each spell, caster berates someone standing nearby"
    ElseIf (Label1.Caption = 55) Then
        Text1.Text = "After each spell, caster briefly appears to be a rotting corpse"
    ElseIf (Label1.Caption = 56) Then
        Text1.Text = "After each spell, caster briefly appears to be on fire"
    ElseIf (Label1.Caption = 57) Then
        Text1.Text = "After each spell, caster briefly appears to bleed from his eyes"
    ElseIf (Label1.Caption = 58) Then
        Text1.Text = "After each spell, caster briefly looks like a photo negative"
    ElseIf (Label1.Caption = 59) Then
        Text1.Text = "After each spell, caster briefly seems to be of the opposite sex"
    ElseIf (Label1.Caption = 60) Then
        Text1.Text = "After each spell, caster briefly sees fire all around him"
    ElseIf (Label1.Caption = 61) Then
        Text1.Text = "After each spell, caster briefly thinks that he’s choking"
    ElseIf (Label1.Caption = 62) Then
        Text1.Text = "After each spell, caster can sense secret doors for 1d4 rounds"
    ElseIf (Label1.Caption = 63) Then
        Text1.Text = "After each spell, caster can’t be magically healed for one hour"
    ElseIf (Label1.Caption = 64) Then
        Text1.Text = "After each spell, caster can’t traverse a doorway for 1d10 rounds"
    ElseIf (Label1.Caption = 65) Then
        Text1.Text = "After each spell, caster dances like a honeybee"
    ElseIf (Label1.Caption = 66) Then
        Text1.Text = "After each spell, caster experiences a burning sensation"
    ElseIf (Label1.Caption = 67) Then
        Text1.Text = "After each spell, caster feels ants crawling all over him"
    ElseIf (Label1.Caption = 68) Then
        Text1.Text = "After each spell, caster feels compelled to wash his hands"
    ElseIf (Label1.Caption = 69) Then
        Text1.Text = "After each spell, caster feels completely alone and isolated"
    ElseIf (Label1.Caption = 70) Then
        Text1.Text = "After each spell, caster feels distractingly hungry"
    ElseIf (Label1.Caption = 71) Then
        Text1.Text = "After each spell, caster feels overwhelmingly dizzy"
    ElseIf (Label1.Caption = 72) Then
        Text1.Text = "After each spell, caster feels transcendent euphoria"
    ElseIf (Label1.Caption = 73) Then
        Text1.Text = "After each spell, caster forgets everyone’s name for one hour"
    ElseIf (Label1.Caption = 74) Then
        Text1.Text = "After each spell, caster forgets his name for one hour"
    ElseIf (Label1.Caption = 75) Then
        Text1.Text = "After each spell, caster glows with infernal radiance"
    ElseIf (Label1.Caption = 76) Then
        Text1.Text = "After each spell, caster growls like a rabid dog"
    ElseIf (Label1.Caption = 77) Then
        Text1.Text = "After each spell, caster has a brief vision of some distant land"
    ElseIf (Label1.Caption = 78) Then
        Text1.Text = "After each spell, caster has a strong craving for twigs and bark"
    ElseIf (Label1.Caption = 79) Then
        Text1.Text = "After each spell, caster is 5% likely to be stricken mute"
    ElseIf (Label1.Caption = 80) Then
        Text1.Text = "After each spell, caster is 25% likely to turn briefly invisible"
    ElseIf (Label1.Caption = 81) Then
        Text1.Text = "After each spell, caster is 30% likely to lose his balance"
    ElseIf (Label1.Caption = 82) Then
        Text1.Text = "After each spell, caster is 60% likely to flap his arms"
    ElseIf (Label1.Caption = 83) Then
        Text1.Text = "After each spell, caster is afraid of his own name"
    ElseIf (Label1.Caption = 84) Then
        Text1.Text = "After each spell, caster is as hairy as an ape for one hour"
    ElseIf (Label1.Caption = 85) Then
        Text1.Text = "After each spell, caster is base AC zero for 1d4 rounds"
    ElseIf (Label1.Caption = 86) Then
        Text1.Text = "After each spell, caster is bathed in an otherworldly green light"
    ElseIf (Label1.Caption = 87) Then
        Text1.Text = "After each spell, caster is blind in one eye for one hour"
    ElseIf (Label1.Caption = 88) Then
        Text1.Text = "After each spell, caster is grief-stricken for 1d10 rounds"
    ElseIf (Label1.Caption = 89) Then
        Text1.Text = "After each spell, caster is hopelessly drunk for 1d4 rounds"
    ElseIf (Label1.Caption = 90) Then
        Text1.Text = "After each spell, caster is immune to bludgeons for 1d4 rounds"
    ElseIf (Label1.Caption = 91) Then
        Text1.Text = "After each spell, caster is immune to missile fire for one round"
    ElseIf (Label1.Caption = 92) Then
        Text1.Text = "After each spell, caster is intensely magnetic for 1d8 rounds"
    ElseIf (Label1.Caption = 93) Then
        Text1.Text = "After each spell, caster is matte black for 1d4 rounds"
    ElseIf (Label1.Caption = 94) Then
        Text1.Text = "After each spell, caster is suddenly facing True North"
    ElseIf (Label1.Caption = 95) Then
        Text1.Text = "After each spell, caster is wracked by existential horror"
    ElseIf (Label1.Caption = 96) Then
        Text1.Text = "After each spell, caster looks like a cadaver for 1d4 rounds"
    ElseIf (Label1.Caption = 97) Then
        Text1.Text = "After each spell, caster makes short, barking cries"
    ElseIf (Label1.Caption = 98) Then
        Text1.Text = "After each spell, caster oozes sweet-smelling oil for 1d4 rounds"
    ElseIf (Label1.Caption = 99) Then
        Text1.Text = "After each spell, caster polymorphs very briefly"
    ElseIf (Label1.Caption = 100) Then
        Text1.Text = "After each spell, caster reeks of alcohol for 2d6 rounds"
    ElseIf (Label1.Caption = 101) Then
        Text1.Text = "After each spell, caster salivates copiously"
    ElseIf (Label1.Caption = 102) Then
        Text1.Text = "After each spell, caster seems withdrawn and despondent"
    ElseIf (Label1.Caption = 103) Then
        Text1.Text = "After each spell, caster shakes like a rag doll for 2d4 seconds"
    ElseIf (Label1.Caption = 104) Then
        Text1.Text = "After each spell, caster shivers uncontrollably for 1d4 rounds"
    ElseIf (Label1.Caption = 105) Then
        Text1.Text = "After each spell, caster shrinks by 10d10% for 1d4 rounds"
    ElseIf (Label1.Caption = 106) Then
        Text1.Text = "After each spell, caster shrinks by 50%"
    ElseIf (Label1.Caption = 107) Then
        Text1.Text = "After each spell, caster smells strongly of turpentine"
    ElseIf (Label1.Caption = 108) Then
        Text1.Text = "After each spell, caster suffers brief visions of carnage"
    ElseIf (Label1.Caption = 109) Then
        Text1.Text = "After each spell, caster suffers disorienting vertigo"
    ElseIf (Label1.Caption = 110) Then
        Text1.Text = "After each spell, caster thinks that he’s drowning"
    ElseIf (Label1.Caption = 111) Then
        Text1.Text = "After each spell, caster thinks that his clothes are on fire"
    ElseIf (Label1.Caption = 112) Then
        Text1.Text = "After each spell, caster trumpets like an elephant"
    ElseIf (Label1.Caption = 113) Then
        Text1.Text = "After each spell, caster vanishes very briefly vanishes"
    ElseIf (Label1.Caption = 114) Then
        Text1.Text = "After each spell, caster’s clothes age 1d100 years"
    ElseIf (Label1.Caption = 115) Then
        Text1.Text = "After each spell, caster’s clothes billow with green smoke"
    ElseIf (Label1.Caption = 116) Then
        Text1.Text = "After each spell, caster’s eyes briefly double in size"
    ElseIf (Label1.Caption = 117) Then
        Text1.Text = "After each spell, caster’s face looks 50 years older"
    ElseIf (Label1.Caption = 118) Then
        Text1.Text = "After each spell, caster’s feet are covered with ash"
    ElseIf (Label1.Caption = 119) Then
        Text1.Text = "After each spell, caster’s hair grows two inches"
    ElseIf (Label1.Caption = 120) Then
        Text1.Text = "After each spell, caster’s hands display classic stigmata"
    ElseIf (Label1.Caption = 121) Then
        Text1.Text = "After each spell, caster’s hands steam wildly"
    ElseIf (Label1.Caption = 122) Then
        Text1.Text = "After each spell, caster’s head turns 360° at the neck, unharmed"
    ElseIf (Label1.Caption = 123) Then
        Text1.Text = "After each spell, caster’s head turns invisible for 1d4 rounds"
    ElseIf (Label1.Caption = 124) Then
        Text1.Text = "After each spell, caster’s heart pounds audibly"
    ElseIf (Label1.Caption = 125) Then
        Text1.Text = "After each spell, caster’s left arm turns to stone for one hour"
    ElseIf (Label1.Caption = 126) Then
        Text1.Text = "After each spell, caster’s spellbook throbs with deep red light"
    ElseIf (Label1.Caption = 127) Then
        Text1.Text = "After each spell, caster’s Strength is halved for one hour"
    ElseIf (Label1.Caption = 128) Then
        Text1.Text = "After each spell, gravity briefly doubles for the caster"
    ElseIf (Label1.Caption = 129) Then
        Text1.Text = "After each spell, he giggles for 1d4-1 rounds"
    ElseIf (Label1.Caption = 130) Then
        Text1.Text = "After each spell, light shines from caster’s mouth for 1d6 rounds"
    ElseIf (Label1.Caption = 131) Then
        Text1.Text = "After each spell, small lumps of ice fall from caster’s nostrils"
    ElseIf (Label1.Caption = 132) Then
        Text1.Text = "After each spell, smoke hangs in the air about the caster"
    ElseIf (Label1.Caption = 133) Then
        Text1.Text = "After each spell, stones near the caster glisten with slime"
    ElseIf (Label1.Caption = 134) Then
        Text1.Text = "After each spell, sunlight is painful to caster for 1d4 rounds"
    ElseIf (Label1.Caption = 135) Then
        Text1.Text = "Alcohol has no effect upon the caster, but cheese is intoxicating"
    ElseIf (Label1.Caption = 136) Then
        Text1.Text = "All holy symbols within 100 yards bear the caster’s image"
    ElseIf (Label1.Caption = 137) Then
        Text1.Text = "All of caster’s clothing is colored safety orange"    
    ElseIf (Label1.Caption = 138) Then
        Text1.Text = "All of caster’s clothing is permanently moist"
    ElseIf (Label1.Caption = 139) Then
        Text1.Text = "All of caster’s enemies with 100 yards vanish until dawn"
    ElseIf (Label1.Caption = 140) Then
        Text1.Text = "All of caster’s fingers are as long as his middle finger"
    ElseIf (Label1.Caption = 141) Then
        Text1.Text = "All of caster’s fingers are clear like glass"
    ElseIf (Label1.Caption = 142) Then
        Text1.Text = "All of caster’s fingers double in thickness"
    ElseIf (Label1.Caption = 143) Then
        Text1.Text = "All of caster’s fingers migrate to one hand"
    ElseIf (Label1.Caption = 144) Then
        Text1.Text = "All of caster’s monetary wealth appears atop the nearest mountain"
    ElseIf (Label1.Caption = 145) Then
        Text1.Text = "All of caster’s monetary wealth is revealed to be counterfeit"
    ElseIf (Label1.Caption = 146) Then
        Text1.Text = "All of caster’s possessions age 1d1000 years"
    ElseIf (Label1.Caption = 147) Then
        Text1.Text = "All of caster’s possessions are thrown 4d6 hours into the future"
    ElseIf (Label1.Caption = 148) Then
        Text1.Text = "All of caster’s possessions have been seized by the government"
    ElseIf (Label1.Caption = 149) Then
        Text1.Text = "All trees within 100 yards form into a tight circle around caster"
    ElseIf (Label1.Caption = 150) Then
        Text1.Text = "All undead within 1d4 miles blame the caster for their undeath"
    ElseIf (Label1.Caption = 151) Then
        Text1.Text = "All undead within 1d4 miles race to the caster’s current location"
    ElseIf (Label1.Caption = 152) Then
        Text1.Text = "All vegetation now within 10 miles is highly toxic to caster"
    ElseIf (Label1.Caption = 153) Then
        Text1.Text = "All vegetation now within 100 yards is invisible to caster"
    ElseIf (Label1.Caption = 154) Then
        Text1.Text = "All who meet caster are 50% likely to think he smells like manure"
    ElseIf (Label1.Caption = 155) Then
        Text1.Text = "All who meet caster are 60% likely to think he’s a lycanthrope"
    ElseIf (Label1.Caption = 156) Then
        Text1.Text = "All who meet caster are 60% likely to think he’s undead"
    ElseIf (Label1.Caption = 157) Then
        Text1.Text = "All within 10 yards of caster are sprayed with viscous ectoplasm"
    ElseIf (Label1.Caption = 158) Then
        Text1.Text = "All within 10 yards of caster attack him for 1d4 rounds"
    ElseIf (Label1.Caption = 159) Then
        Text1.Text = "Alternating pages of caster’s spellbook are indestructible"
    ElseIf (Label1.Caption = 160) Then
        Text1.Text = "An accurate illusion of caster copies his movements one mile away"
    ElseIf (Label1.Caption = 161) Then
        Text1.Text = "An illusory statue of the caster stands at this spot for one year"
    ElseIf (Label1.Caption = 162) Then
        Text1.Text = "An image of caster’s beating heart hovers in the nearest doorway"
    ElseIf (Label1.Caption = 163) Then
        Text1.Text = "An image of the caster’s head hovers over his actual head"
    ElseIf (Label1.Caption = 163) Then
        Text1.Text = "An image of the caster’s head hovers over his actual head"
    ElseIf (Label1.Caption = 164) Then
        Text1.Text = "An image the of caster’s beating heart hovers over his head"
    ElseIf (Label1.Caption = 165) Then
        Text1.Text = "Any Abjurations currently affecting the caster are Dispelled"
    ElseIf (Label1.Caption = 166) Then
        Text1.Text = "Any armor that the caster is wearing right now shrinks by 80%"
    ElseIf (Label1.Caption = 167) Then
        Text1.Text = "Any armor that the caster is wearing right now vanishes forever"
    ElseIf (Label1.Caption = 168) Then
        Text1.Text = "Any arrow striking the caster disintegrates in 1d4 rounds"
    ElseIf (Label1.Caption = 169) Then
        Text1.Text = "Any arrow striking the caster inflicts equal damage on its archer"
    ElseIf (Label1.Caption = 170) Then
        Text1.Text = "Any attack-based spell cast by caster is 10% likely to affect him"
    ElseIf (Label1.Caption = 171) Then
        Text1.Text = "Any attack-based spell cast by caster is delayed 1d4 rounds"
    ElseIf (Label1.Caption = 172) Then
        Text1.Text = "Any attempt to change shape locks the caster into that new shape"
    ElseIf (Label1.Caption = 173) Then
        Text1.Text = "Any attempt to change shape makes the caster forget his true form"
    ElseIf (Label1.Caption = 174) Then
        Text1.Text = "Any attempt to change shape will age the caster 1d10 years"
    ElseIf (Label1.Caption = 175) Then
        Text1.Text = "Any attempt to change shape will be only partially successful"
    ElseIf (Label1.Caption = 176) Then
        Text1.Text = "Any attempt to change shape will cause the caster to take root"
    ElseIf (Label1.Caption = 177) Then
        Text1.Text = "Any attempt to change shape will leave his feet unchanged"
    ElseIf (Label1.Caption = 178) Then
        Text1.Text = "Any attempt to change shape will make the caster bald forever"
    ElseIf (Label1.Caption = 179) Then
        Text1.Text = "Any attempt to change shape will render the caster genderless"
    ElseIf (Label1.Caption = 180) Then
        Text1.Text = "Any attempt to change shape will teleport the caster 1d1000 miles"
    ElseIf (Label1.Caption = 181) Then
        Text1.Text = "Any attempt to change shape will teleport the caster 1d1000 miles"
    ElseIf (Label1.Caption = 182) Then
        Text1.Text = "Any attempt to change shape will teleport the caster to this spot"
    ElseIf (Label1.Caption = 183) Then
        Text1.Text = "Any attempt to change shape will turn him into 2d12 ducklings"
    ElseIf (Label1.Caption = 184) Then
        Text1.Text = "Any attempt to change shape will turn the caster inside-out"
    ElseIf (Label1.Caption = 185) Then
        Text1.Text = "Any attempt to change shape will turn the caster into a geranium"
    ElseIf (Label1.Caption = 186) Then
        Text1.Text = "Any attempt to change shape will turn the caster into a monkey"
    ElseIf (Label1.Caption = 187) Then
        Text1.Text = "Any attempt to change shape will turn the caster into a pelican"
    ElseIf (Label1.Caption = 188) Then
        Text1.Text = "Any attempt to change shape will turn the caster into a penguin"
    ElseIf (Label1.Caption = 189) Then
        Text1.Text = "Any attempt to change shape will turn the caster into a rabbit"
    ElseIf (Label1.Caption = 190) Then
        Text1.Text = "Any attempt to change shape will turn the caster into a shrubbery"
    ElseIf (Label1.Caption = 191) Then
        Text1.Text = "Any attempt to change shape will turn the caster into a snowman"
    ElseIf (Label1.Caption = 192) Then
        Text1.Text = "Any attempt to change shape will turn the caster into a toddler"
    ElseIf (Label1.Caption = 193) Then
        Text1.Text = "Any attempt to change shape will turn the caster into a troll"
    ElseIf (Label1.Caption = 194) Then
        Text1.Text = "Any attempt to change shape will turn the caster into a wax dummy"
    ElseIf (Label1.Caption = 195) Then
        Text1.Text = "Any attempt to read caster’s mind reveals a homicidal maniac"
    ElseIf (Label1.Caption = 196) Then
        Text1.Text = "Any attempt to read caster’s mind reveals an absolute void"
    ElseIf (Label1.Caption = 197) Then
        Text1.Text = "Any attempt to use rope inspires the caster to hang himself"
    ElseIf (Label1.Caption = 198) Then
        Text1.Text = "Any attempt to use rope leaves caster hopelessly entangled"
    ElseIf (Label1.Caption = 199) Then
        Text1.Text = "Any attempt to use rope leaves hideous welts on the caster’s body"
    ElseIf (Label1.Caption = 200) Then
        Text1.Text = "Any blade that has drawn the caster’s blood is invisible to him"
    ElseIf (Label1.Caption = 201) Then
        Text1.Text = "Any bread that caster bakes remains warm until it’s eaten"
    ElseIf (Label1.Caption = 202) Then
        Text1.Text = "Any building that the caster enters appears to catch fire"
    ElseIf (Label1.Caption = 203) Then
        Text1.Text = "Any building that the caster enters ejects him forcefully"
    ElseIf (Label1.Caption = 204) Then
        Text1.Text = "Any clothing worn by caster is invisible to him while he wears it"
    ElseIf (Label1.Caption = 205) Then
        Text1.Text = "Any clothing worn by caster smells like carrion while he wears it"
    ElseIf (Label1.Caption = 206) Then
        Text1.Text = "Any coins in caster’s possession are gold-plated"
    ElseIf (Label1.Caption = 207) Then
        Text1.Text = "Any coins in caster’s possession become copper pieces"
    ElseIf (Label1.Caption = 208) Then
        Text1.Text = "Any coins now carried by caster are water-soluble for 1d4 weeks"
    ElseIf (Label1.Caption = 209) Then
        Text1.Text = "Any coins now carried by caster ignite and burn like tinder"
    ElseIf (Label1.Caption = 210) Then
        Text1.Text = "Any creature Summoned by caster emerges from his mouth"
    ElseIf (Label1.Caption = 211) Then
        Text1.Text = "Any creatures Summoned near caster are invisible to him"
    ElseIf (Label1.Caption = 212) Then
        Text1.Text = "Any creatures Summoned near caster immediately befriend him"
    ElseIf (Label1.Caption = 213) Then
        Text1.Text = "Any damage against caster is rolled twice, using the higher roll"
    ElseIf (Label1.Caption = 214) Then
        Text1.Text = "Any damage against caster is rolled twice, using the lower roll"
    ElseIf (Label1.Caption = 215) Then
        Text1.Text = "Any electricity-based magic used by caster discharges on him"
    ElseIf (Label1.Caption = 215) Then
        Text1.Text = "Any electricity-based magic used by caster discharges on him"
    ElseIf (Label1.Caption = 216) Then
        Text1.Text = "Any electricity-based magic used by caster reeks of ozone"
    ElseIf (Label1.Caption = 217) Then
        Text1.Text = "Any fire extinguished by caster rekindles itself 1d4 turns later"
    ElseIf (Label1.Caption = 218) Then
        Text1.Text = "Any fire-based spell used by caster has only 25% of normal range"
    ElseIf (Label1.Caption = 219) Then
        Text1.Text = "Any fires set by caster are invisible for 2d6 hours"
    ElseIf (Label1.Caption = 220) Then
        Text1.Text = "Any fires set by caster attract undead like moths to a candle"
    ElseIf (Label1.Caption = 221) Then
        Text1.Text = "Any fires set by caster jingle like wind chimes while they burn"
    ElseIf (Label1.Caption = 222) Then
        Text1.Text = "Any fires set by caster make those near it appear to be undead"
    ElseIf (Label1.Caption = 223) Then
        Text1.Text = "Any fires set by caster produce no heat"
    ElseIf (Label1.Caption = 224) Then
        Text1.Text = "Any fires set by caster produce no smoke"
    ElseIf (Label1.Caption = 225) Then
        Text1.Text = "Any fires set by caster whisper vague threats against him"
    ElseIf (Label1.Caption = 226) Then
        Text1.Text = "Any food now carried by caster combusts"
    ElseIf (Label1.Caption = 227) Then
        Text1.Text = "Any food now carried by caster is 10X as nutritious"
    ElseIf (Label1.Caption = 228) Then
        Text1.Text = "Any food now carried by caster is fused into glass"
    ElseIf (Label1.Caption = 229) Then
        Text1.Text = "Any food now carried by caster is sealed in airtight tin cans"
    ElseIf (Label1.Caption = 230) Then
        Text1.Text = "Any food now carried by caster is toxic to Dwarves"
    ElseIf (Label1.Caption = 231) Then
        Text1.Text = "Any food now carried by caster smells like carrion"
    ElseIf (Label1.Caption = 232) Then
        Text1.Text = "Any food now carried by caster turns to ice"
    ElseIf (Label1.Caption = 233) Then
        Text1.Text = "Any food now carried by caster turns to iron"
    ElseIf (Label1.Caption = 234) Then
        Text1.Text = "Any food now carried by caster turns to spun sugar"
    ElseIf (Label1.Caption = 235) Then
        Text1.Text = "Any gems in caster’s possession are replaced by lumps of gelatin"
    ElseIf (Label1.Caption = 236) Then
        Text1.Text = "Any hammer thrown by caster returns to his hand one round later"
    ElseIf (Label1.Caption = 237) Then
        Text1.Text = "Any horse ridden by caster suffers no fatigue while he rides it"
    ElseIf (Label1.Caption = 238) Then
        Text1.Text = "Any intelligent weapons now carried by caster hate him forever"
    ElseIf (Label1.Caption = 239) Then
        Text1.Text = "Any intelligent weapons seen by caster look vaguely familiar"
    ElseIf (Label1.Caption = 240) Then
        Text1.Text = "Any magic currently affecting the caster is Dispelled"
    ElseIf (Label1.Caption = 241) Then
        Text1.Text = "Any magic currently affecting the caster is suppressed until dawn"
    ElseIf (Label1.Caption = 242) Then
        Text1.Text = "Any magic items owned by caster appear in a heap nearby"
    ElseIf (Label1.Caption = 243) Then
        Text1.Text = "Any magic items owned by caster are non-functional for 1d10 days"
    ElseIf (Label1.Caption = 244) Then
        Text1.Text = "Any magical scrolls now carried by caster are fireproof"
    ElseIf (Label1.Caption = 245) Then
        Text1.Text = "Any magical scrolls now carried by caster are forgeries"
    ElseIf (Label1.Caption = 246) Then
        Text1.Text = "Any magical scrolls now carried by caster are subtly tainted"
    ElseIf (Label1.Caption = 247) Then
        Text1.Text = "Any magical scrolls now carried by caster discharge spontaneously"
    ElseIf (Label1.Caption = 248) Then
        Text1.Text = "Any magical scrolls now carried by caster turn to steel"
    ElseIf (Label1.Caption = 249) Then
        Text1.Text = "Any metal object carried by caster is 90% transparent"
    ElseIf (Label1.Caption = 250) Then
        Text1.Text = "Any metal object carried by caster seems 10x its normal weight"
    ElseIf (Label1.Caption = 251) Then
        Text1.Text = "Any metal that caster is carrying turns to liquid like mercury"
    ElseIf (Label1.Caption = 252) Then
        Text1.Text = "Any missile fired at caster is 10% likely to explode when it hits"
    ElseIf (Label1.Caption = 253) Then
        Text1.Text = "Any missile fired at caster is at a -3 penalty to hit him"
    ElseIf (Label1.Caption = 254) Then
        Text1.Text = "Any missile fired by caster is 10% likely to vanish in flight"
    ElseIf (Label1.Caption = 255) Then
        Text1.Text = "Any missile shot by caster is destroyed by lightning mid-flight"
    ElseIf (Label1.Caption = 256) Then
        Text1.Text = "Any missile striking caster is 10% likely to be just an illusion"
    ElseIf (Label1.Caption = 257) Then
        Text1.Text = "Any mountain more than one mile from caster is invisible to him"
    ElseIf (Label1.Caption = 258) Then
        Text1.Text = "Any ranged spell used by caster seems to issue from his eyes"
    ElseIf (Label1.Caption = 259) Then
        Text1.Text = "Any ranged spell used by caster seems to issue from someone else"
    ElseIf (Label1.Caption = 260) Then
        Text1.Text = "Any rope currently carried by caster doubles in length"
    ElseIf (Label1.Caption = 261) Then
        Text1.Text = "Any rope currently carried by caster turns to braided gold wire"
    ElseIf (Label1.Caption = 262) Then
        Text1.Text = "Any rope that caster is now carrying becomes frictionless"
    ElseIf (Label1.Caption = 263) Then
        Text1.Text = "Any rope that caster is now carrying is soaked with lamp oil"
    ElseIf (Label1.Caption = 264) Then
        Text1.Text = "Any shield held by caster appears to be made of Swiss cheese"
    ElseIf (Label1.Caption = 265) Then
        Text1.Text = "Any shield held by caster appears to weigh 100 pounds"
    ElseIf (Label1.Caption = 266) Then
        Text1.Text = "Any shield held by caster gains a +1 bonus while he holds it"
    ElseIf (Label1.Caption = 267) Then
        Text1.Text = "Any shield held by caster is ethereal in the presence of weapons"
    ElseIf (Label1.Caption = 268) Then
        Text1.Text = "Any shield held by caster is impervious to magical fire"
    ElseIf (Label1.Caption = 269) Then
        Text1.Text = "Any spells cast by caster are accompanied by twinkling lights"
    ElseIf (Label1.Caption = 270) Then
        Text1.Text = "Any spells cast by caster upon himself have an undesirable effect"
    ElseIf (Label1.Caption = 271) Then
        Text1.Text = "Any spells cast by caster upon himself lapse after one round"
    ElseIf (Label1.Caption = 272) Then
        Text1.Text = "Any spells cast by caster within the last hour are negated"
    ElseIf (Label1.Caption = 273) Then
        Text1.Text = "Any spells caster now has memorized will fail when he casts them"
    ElseIf (Label1.Caption = 274) Then
        Text1.Text = "Any undead in the area attack the caster but ignore everyone else"
    ElseIf (Label1.Caption = 275) Then
        Text1.Text = "Any undead in the area flee from the caster for 2d10 rounds"
    ElseIf (Label1.Caption = 276) Then
        Text1.Text = "Any wood within 25 yards flies toward the caster for 1d10 rounds"
    ElseIf (Label1.Caption = 277) Then
        Text1.Text = "Any writing implement used by caster breaks, runs dry, etc."
    ElseIf (Label1.Caption = 278) Then
        Text1.Text = "Anyone attempting to rob caster must tell him about it beforehand"
    ElseIf (Label1.Caption = 279) Then
        Text1.Text = "Anyone drinking a potion near caster looks like him until sunset"
    ElseIf (Label1.Caption = 280) Then
        Text1.Text = "Anyone drinking a potion shrinks by 50% for its duration"
    ElseIf (Label1.Caption = 281) Then
        Text1.Text = "Anyone in caster’s presence can’t employ Direction Sense"
    ElseIf (Label1.Caption = 282) Then
        Text1.Text = "Anyone in caster’s presence thinks that he represents True North"
    ElseIf (Label1.Caption = 283) Then
        Text1.Text = "Anyone related to caster by blood is invisible to him"
    ElseIf (Label1.Caption = 284) Then
        Text1.Text = "Anyone slain by caster becomes invisible upon death"
    ElseIf (Label1.Caption = 285) Then
        Text1.Text = "Anyone trying to pick caster’s pocket shrinks by 50%"
    ElseIf (Label1.Caption = 286) Then
        Text1.Text = "Anyone trying to scry the caster’s whereabouts sees this location"
    ElseIf (Label1.Caption = 287) Then
        Text1.Text = "Anyone voluntarily struck by caster’s magic resents him for it"
    ElseIf (Label1.Caption = 288) Then
        Text1.Text = "Anyone who knows caster’s name gives him an offensive nickname"
    ElseIf (Label1.Caption = 289) Then
        Text1.Text = "Anyone who looks deep into caster’s mouth risks insanity"
    ElseIf (Label1.Caption = 290) Then
        Text1.Text = "Anything caster drinks is 50% likely to fall from his mouth"
    ElseIf (Label1.Caption = 291) Then
        Text1.Text = "Anything written by caster appears as gibberish to everyone else"
    ElseIf (Label1.Caption = 292) Then
        Text1.Text = "Artifacts react unpredictably when caster attempts to use them"
    ElseIf (Label1.Caption = 293) Then
        Text1.Text = "Before each spell, caster must address someone who isn’t there"
    ElseIf (Label1.Caption = 294) Then
        Text1.Text = "Before each spell, caster must anoint his head with water"
    ElseIf (Label1.Caption = 295) Then
        Text1.Text = "Before each spell, caster must bark like a dog for 2d6 seconds"
    ElseIf (Label1.Caption = 296) Then
        Text1.Text = "Before each spell, caster must bite a gold coin"
    ElseIf (Label1.Caption = 297) Then
        Text1.Text = "Before each spell, caster must blaspheme some god of chaos"
    ElseIf (Label1.Caption = 298) Then
        Text1.Text = "Before each spell, caster must claim that his shoes are too tight"
    ElseIf (Label1.Caption = 299) Then
        Text1.Text = "Before each spell, caster must claim to be invincible"
    ElseIf (Label1.Caption = 300) Then
        Text1.Text = "Before each spell, caster must clear his throat loudly"
    ElseIf (Label1.Caption = 301) Then
        Text1.Text = "Before each spell, caster must confess an embarrassing secret"
    ElseIf (Label1.Caption = 301) Then
        Text1.Text = "Before each spell, caster must confess an embarrassing secret"
    ElseIf (Label1.Caption = 302) Then
        Text1.Text = "Before each spell, caster must confess that he’s a charlatan"
    ElseIf (Label1.Caption = 303) Then
        Text1.Text = "Before each spell, caster must crack his knuckles"
    ElseIf (Label1.Caption = 304) Then
        Text1.Text = "Before each spell, caster must drop a gold coin to the ground"
    ElseIf (Label1.Caption = 305) Then
        Text1.Text = "Before each spell, caster must give himself permission to cast it"
    ElseIf (Label1.Caption = 306) Then
        Text1.Text = "Before each spell, caster must hold his breath for 1d10 seconds"
    ElseIf (Label1.Caption = 307) Then
        Text1.Text = "Before each spell, caster must ingest a pinch of dust"
    ElseIf (Label1.Caption = 308) Then
        Text1.Text = "Before each spell, caster must insult a close friend"
    ElseIf (Label1.Caption = 309) Then
        Text1.Text = "Before each spell, caster must invoke some monstrous entity"
    ElseIf (Label1.Caption = 310) Then
        Text1.Text = "Before each spell, caster must issue what sounds like a prophecy"
    ElseIf (Label1.Caption = 311) Then
        Text1.Text = "Before each spell, caster must light a small candle"
    ElseIf (Label1.Caption = 312) Then
        Text1.Text = "Before each spell, caster must make a new and improbable vow"
    ElseIf (Label1.Caption = 313) Then
        Text1.Text = "Before each spell, caster must make an embarrassing admission"
    ElseIf (Label1.Caption = 314) Then
        Text1.Text = "Before each spell, caster must pat himself on the head"
    ElseIf (Label1.Caption = 315) Then
        Text1.Text = "Before each spell, caster must pluck 1d6 hairs from his head"
    ElseIf (Label1.Caption = 316) Then
        Text1.Text = "Before each spell, caster must predict that he’ll die by sunset"
    ElseIf (Label1.Caption = 317) Then
        Text1.Text = "Before each spell, caster must prick his finger with a rusty pin"
    ElseIf (Label1.Caption = 318) Then
        Text1.Text = "Before each spell, caster must profess a thirst for human blood"
    ElseIf (Label1.Caption = 319) Then
        Text1.Text = "Before each spell, caster must profess love for someone nearby"
    ElseIf (Label1.Caption = 320) Then
        Text1.Text = "Before each spell, caster must promise to change his name"
    ElseIf (Label1.Caption = 321) Then
        Text1.Text = "Before each spell, caster must remove one article of clothing"
    ElseIf (Label1.Caption = 322) Then
        Text1.Text = "Before each spell, caster must say ""Magic is my business."""
    ElseIf (Label1.Caption = 323) Then
        Text1.Text = "Before each spell, caster must say ""My God, it’s full of stars."""
    ElseIf (Label1.Caption = 324) Then
        Text1.Text = "Before each spell, caster must say ""The prophecy is fulfilled."""
    ElseIf (Label1.Caption = 325) Then
        Text1.Text = "Before each spell, caster must say ""This probably won’t work."""
    ElseIf (Label1.Caption = 326) Then
        Text1.Text = "Before each spell, caster must shed at least 1d4 tears"
    ElseIf (Label1.Caption = 327) Then
        Text1.Text = "Before each spell, caster must shout a different prime number"
    ElseIf (Label1.Caption = 328) Then
        Text1.Text = "Before each spell, caster must snap a twig or the like"
    ElseIf (Label1.Caption = 329) Then
        Text1.Text = "Before each spell, caster must speak a new and original rhyme"
    ElseIf (Label1.Caption = 330) Then
        Text1.Text = "Before each spell, caster must speak a new and relevant pun"
    ElseIf (Label1.Caption = 331) Then
        Text1.Text = "Before each spell, caster must speak ill of a good friend"
    ElseIf (Label1.Caption = 332) Then
        Text1.Text = "Before each spell, caster must tear one article of clothing"
    ElseIf (Label1.Caption = 333) Then
        Text1.Text = "Before each spell, caster must tie a knot in a piece of string"
    ElseIf (Label1.Caption = 334) Then
        Text1.Text = "Before each spell, caster must touch his eyes, ears, and nose"
    ElseIf (Label1.Caption = 335) Then
        Text1.Text = "Before each spell, caster must touch liquid water"
    ElseIf (Label1.Caption = 336) Then
        Text1.Text = "Before each spell, caster must trace a circle in the air"
    ElseIf (Label1.Caption = 337) Then
        Text1.Text = "Before each spell, caster must vow that this is his final spell"
    ElseIf (Label1.Caption = 338) Then
        Text1.Text = "Beneficial magic potions have an opposite effect upon the caster"
    ElseIf (Label1.Caption = 339) Then
        Text1.Text = "Bits of flesh fall from caster’s body until he’s a bare skeleton"
    ElseIf (Label1.Caption = 340) Then
        Text1.Text = "Blades seem extraordinarily dull while caster wields them"
    ElseIf (Label1.Caption = 341) Then
        Text1.Text = "Caster accidentally creates a virulent plague in his workshop"
    ElseIf (Label1.Caption = 342) Then
        Text1.Text = "Caster accuses his nearest ally of murdering him"
    ElseIf (Label1.Caption = 343) Then
        Text1.Text = "Caster acquires an exact copy of every non-magical thing he owns"
    ElseIf (Label1.Caption = 344) Then
        Text1.Text = "Caster acquires lycanthropy, but only in his left leg"
    ElseIf (Label1.Caption = 345) Then
        Text1.Text = "Caster acquires proficiency in some weapon that will never exist"
    ElseIf (Label1.Caption = 346) Then
        Text1.Text = "Caster addresses everyone he knows by his own name"
    ElseIf (Label1.Caption = 347) Then
        Text1.Text = "Caster adopts a habit of nightly self-flagellation"
    ElseIf (Label1.Caption = 348) Then
        Text1.Text = "Caster adopts a universally obscene gesture as his trademark"
    ElseIf (Label1.Caption = 349) Then
        Text1.Text = "Caster adopts bizarre rituals concerning the preparation of food"
    ElseIf (Label1.Caption = 350) Then
        Text1.Text = "Caster adopts fastidious standards of hygiene"
    ElseIf (Label1.Caption = 351) Then
        Text1.Text = "Caster adopts some unlikely animal as a kind of spirit totem"
    ElseIf (Label1.Caption = 352) Then
        Text1.Text = "Caster adopts some unlikely object as a kind of holy symbol"
    ElseIf (Label1.Caption = 353) Then
        Text1.Text = "Caster adopts the next religion he encounters for the first time"
    ElseIf (Label1.Caption = 354) Then
        Text1.Text = "Caster ages 1d10 years per hour until sunset tonight"
    ElseIf (Label1.Caption = 355) Then
        Text1.Text = "Caster ages 1d10 years/round for 2 turns, then reverts to normal"
    ElseIf (Label1.Caption = 356) Then
        Text1.Text = "Caster ages backwards 2d4 years over that many rounds"
    ElseIf (Label1.Caption = 357) Then
        Text1.Text = "Caster ages normally but forever retains his current appearance"
    ElseIf (Label1.Caption = 358) Then
        Text1.Text = "Caster ages one year per day spent on open water"
    ElseIf (Label1.Caption = 359) Then
        Text1.Text = "Caster ages one year per mile that he travels away from this spot"
    ElseIf (Label1.Caption = 360) Then
        Text1.Text = "Caster always appears healthy and wealthy"
    ElseIf (Label1.Caption = 361) Then
        Text1.Text = "Caster always appears sickly and destitute"
    ElseIf (Label1.Caption = 362) Then
        Text1.Text = "Caster always feels as if the temperature is what it is right now"
    ElseIf (Label1.Caption = 363) Then
        Text1.Text = "Caster always pays 10% more than the asking price"
    ElseIf (Label1.Caption = 364) Then
        Text1.Text = "Caster always sees his surroundings as misty and fog-shrouded"
    ElseIf (Label1.Caption = 365) Then
        Text1.Text = "Caster always thinks it’s fifty degrees colder than it really is"
    ElseIf (Label1.Caption = 366) Then
        Text1.Text = "Caster always thinks that there’s one more step in the staircase"
    ElseIf (Label1.Caption = 367) Then
        Text1.Text = "Caster and everyone else forgets and can’t discern his age"
    ElseIf (Label1.Caption = 368) Then
        Text1.Text = "Caster and nearest intelligent weapon exchange personalities"
    ElseIf (Label1.Caption = 369) Then
        Text1.Text = "Caster and one nearby ally teleport to the caster’s home"
    ElseIf (Label1.Caption = 370) Then
        Text1.Text = "Caster annoys everyone by insisting that he’s ambidextrous"
    ElseIf (Label1.Caption = 371) Then
        Text1.Text = "Caster appears increasingly decrepit as the day wears on"
    ElseIf (Label1.Caption = 372) Then
        Text1.Text = "Caster appears to be a bare skeleton from the waist down"
    ElseIf (Label1.Caption = 373) Then
        Text1.Text = "Caster appears to be a bare skeleton from the waist up"
    ElseIf (Label1.Caption = 374) Then
        Text1.Text = "Caster appears to be at full health, no matter how badly injured"
    ElseIf (Label1.Caption = 375) Then
        Text1.Text = "Caster appears to be bleeding profusely whenever he’s indoors"
    ElseIf (Label1.Caption = 376) Then
        Text1.Text = "Caster appears to be composed of translucent quartz"
    ElseIf (Label1.Caption = 377) Then
        Text1.Text = "Caster appears to be covered in ugly scales for one day each week"
    ElseIf (Label1.Caption = 378) Then
        Text1.Text = "Caster appears to be made of countless flesh-colored pebbles"
    ElseIf (Label1.Caption = 379) Then
        Text1.Text = "Caster appears to be made out of bricks until sunset tomorrow"
    ElseIf (Label1.Caption = 380) Then
        Text1.Text = "Caster appears to be of a different species while sleeping"
    ElseIf (Label1.Caption = 381) Then
        Text1.Text = "Caster appears to be of opposite sex while brandishing a shield"
    ElseIf (Label1.Caption = 382) Then
        Text1.Text = "Caster appears to be on fire while his spellbook is open"
    ElseIf (Label1.Caption = 383) Then
        Text1.Text = "Caster appears to be operating his body from a remote location"
    ElseIf (Label1.Caption = 384) Then
        Text1.Text = "Caster appears to be undead for one hour after each meal"
    ElseIf (Label1.Caption = 385) Then
        Text1.Text = "Caster appears to be undead while in the presence of undead"
    ElseIf (Label1.Caption = 386) Then
        Text1.Text = "Caster appears to be weathered like an ancient statue"
    ElseIf (Label1.Caption = 387) Then
        Text1.Text = "Caster appears to have a railroad spike jutting from his forehead"
    ElseIf (Label1.Caption = 388) Then
        Text1.Text = "Caster appears to have been carved from wood with an axe"
    ElseIf (Label1.Caption = 389) Then
        Text1.Text = "Caster appears to have been crafted out of clay by children"
    ElseIf (Label1.Caption = 390) Then
        Text1.Text = "Caster appears to have been torn apart and hastily reassembled"
    ElseIf (Label1.Caption = 391) Then
        Text1.Text = "Caster appears to shrivel like a raisin after each casting"
    ElseIf (Label1.Caption = 392) Then
        Text1.Text = "Caster appears translucent to anyone of the opposite sex"
    ElseIf (Label1.Caption = 393) Then
        Text1.Text = "Caster asks Elves if they can supply him with fudge cookies"
    ElseIf (Label1.Caption = 394) Then
        Text1.Text = "Caster ate the last of the rations that his party was carrying"
    ElseIf (Label1.Caption = 395) Then
        Text1.Text = "Caster ate two or three pounds of apple seeds this morning"
    ElseIf (Label1.Caption = 396) Then
        Text1.Text = "Caster attempts to drink every potion he sees"
    ElseIf (Label1.Caption = 397) Then
        Text1.Text = "Caster attracts undead in any town he enters"
    ElseIf (Label1.Caption = 398) Then
        Text1.Text = "Caster attracts zealous sycophants wherever he goes"
    ElseIf (Label1.Caption = 399) Then
        Text1.Text = "Caster automatically believes that his own illusions are real"
    ElseIf (Label1.Caption = 400) Then
        Text1.Text = "Caster awakens to find that the last 1d8 hours were only a dream"
    ElseIf (Label1.Caption = 401) Then
        Text1.Text = "Caster bears the birthmark of the lineage of powerful kings"
    ElseIf (Label1.Caption = 402) Then
        Text1.Text = "Caster becomes disturbingly frenetic until sunset"
    ElseIf (Label1.Caption = 403) Then
        Text1.Text = "Caster becomes flat as a sheet of parchment for 2d6 rounds"
    ElseIf (Label1.Caption = 404) Then
        Text1.Text = "Caster becomes increasingly simian as the days wear on"
    ElseIf (Label1.Caption = 405) Then
        Text1.Text = "Caster becomes invisible to anyone who successfully Charms him"
    ElseIf (Label1.Caption = 406) Then
        Text1.Text = "Caster becomes lost if he enters a cave by himself"
    ElseIf (Label1.Caption = 407) Then
        Text1.Text = "Caster becomes lost if he enters a forest by himself"
    ElseIf (Label1.Caption = 408) Then
        Text1.Text = "Caster becomes powerfully addicted to necromantic magic"
    ElseIf (Label1.Caption = 409) Then
        Text1.Text = "Caster becomes powerfully addicted to Chaos Bursts"
    ElseIf (Label1.Caption = 410) Then
        Text1.Text = "Caster becomes tightly stuck to the next chair in which he sits"
    ElseIf (Label1.Caption = 411) Then
        Text1.Text = "Caster becomes unconscious when he becomes invisible"
    ElseIf (Label1.Caption = 412) Then
        Text1.Text = "Caster becomes violently ill if he eats near a fire"
    ElseIf (Label1.Caption = 413) Then
        Text1.Text = "Caster becomes visibly anxious at the sight of holy water"
    ElseIf (Label1.Caption = 414) Then
        Text1.Text = "Caster begins aging backwards, one year per round"
    ElseIf (Label1.Caption = 415) Then
        Text1.Text = "Caster begins growing one inch per week"
    ElseIf (Label1.Caption = 416) Then
        Text1.Text = "Caster begins his conversations with an insulting comment"
    ElseIf (Label1.Caption = 417) Then
        Text1.Text = "Caster begins to resemble the next person who touches him"
    ElseIf (Label1.Caption = 418) Then
        Text1.Text = "Caster begins worshipping his spellbook with burnt offerings"
     ElseIf (Label1.Caption = 419) Then
        Text1.Text = "Caster believes that a nearby sheep is his polymorphed true love"
     ElseIf (Label1.Caption = 420) Then
        Text1.Text = "Caster briefly turns translucent after casting a spell"
     ElseIf (Label1.Caption = 421) Then
        Text1.Text = "Caster burns with homicidal rage whenever he’s struck by magic"
     ElseIf (Label1.Caption = 422) Then
        Text1.Text = "Caster can alter his weight by up to 50% at will"
     ElseIf (Label1.Caption = 423) Then
        Text1.Text = "Caster can always sense his location relative to this location"
     ElseIf (Label1.Caption = 424) Then
        Text1.Text = "Caster can appear to be 50% fatter at will"
     ElseIf (Label1.Caption = 425) Then
        Text1.Text = "Caster can appraise gems by tasting them"
     ElseIf (Label1.Caption = 426) Then
        Text1.Text = "Caster can ask three questions of the next tree he touches"
     ElseIf (Label1.Caption = 427) Then
        Text1.Text = "Caster can assess the purity of any metal by tasting it"
     ElseIf (Label1.Caption = 428) Then
        Text1.Text = "Caster can be accurately described as ""frumious"""
    ElseIf (Label1.Caption = 429) Then
        Text1.Text = "Caster can be injured but not killed by any bludgeoning weapon"
    ElseIf (Label1.Caption = 430) Then
        Text1.Text = "Caster can be injured but not killed by any female creature"
    ElseIf (Label1.Caption = 431) Then
        Text1.Text = "Caster can be injured but not killed by any male creature"
    ElseIf (Label1.Caption = 432) Then
        Text1.Text = "Caster can be injured by fire, but it can’t kill him"
    ElseIf (Label1.Caption = 433) Then
        Text1.Text = "Caster can be injured by metal weapons, but they can’t kill him"
    ElseIf (Label1.Caption = 434) Then
        Text1.Text = "Caster can be injured normally but can only be slain by fire"
    ElseIf (Label1.Caption = 435) Then
        Text1.Text = "Caster can be injured normally but can only be slain by magic"
    ElseIf (Label1.Caption = 436) Then
        Text1.Text = "Caster can become invisible at will while he’s knee-deep in snow"
    ElseIf (Label1.Caption = 437) Then
        Text1.Text = "Caster can become invisible while standing neck-deep in water"
    ElseIf (Label1.Caption = 438) Then
        Text1.Text = "Caster can breathe underwater, but he always smells like a fish"
    ElseIf (Label1.Caption = 439) Then
        Text1.Text = "Caster can carry any weight of books but only in his bare hands"
    ElseIf (Label1.Caption = 440) Then
        Text1.Text = "Caster can cause one creature near him to turn to iron"
    ElseIf (Label1.Caption = 441) Then
        Text1.Text = "Caster can cause one nearby person to age 1d10 years"
    ElseIf (Label1.Caption = 442) Then
        Text1.Text = "Caster can change the size of his ears at will"
    ElseIf (Label1.Caption = 443) Then
        Text1.Text = "Caster can conjure apples out of thin air, one at a time"
    ElseIf (Label1.Caption = 444) Then
        Text1.Text = "Caster can control any undead skeletons now within 100 yards"
    ElseIf (Label1.Caption = 445) Then
        Text1.Text = "Caster can detach either of his hands at will"
    ElseIf (Label1.Caption = 446) Then
        Text1.Text = "Caster can detach his head easily but dies if he does so"
    ElseIf (Label1.Caption = 447) Then
        Text1.Text = "Caster can detect non-magical fire within 500 yards"
    ElseIf (Label1.Caption = 448) Then
        Text1.Text = "Caster can detect the nearest potable water at will"
    ElseIf (Label1.Caption = 449) Then
        Text1.Text = "Caster can detect the presence of elementals within 100 yards"
    ElseIf (Label1.Caption = 450) Then
        Text1.Text = "Caster can detect True East at will"
    ElseIf (Label1.Caption = 451) Then
        Text1.Text = "Caster can discern a person’s age by touching him"
    ElseIf (Label1.Caption = 452) Then
        Text1.Text = "Caster can discern a tree’s age by touching it"
    ElseIf (Label1.Caption = 453) Then
        Text1.Text = "Caster can discern whether people are really unconscious"
    ElseIf (Label1.Caption = 454) Then
        Text1.Text = "Caster can discern which spells a magic user has memorized"
    ElseIf (Label1.Caption = 455) Then
        Text1.Text = "Caster can disgorge a pound of sawdust once per day"
    ElseIf (Label1.Caption = 456) Then
        Text1.Text = "Caster can double his spells’ range if he’s carrying no metal"
    ElseIf (Label1.Caption = 457) Then
        Text1.Text = "Caster can double his weight for up to 1d4 rounds per day"
    ElseIf (Label1.Caption = 458) Then
        Text1.Text = "Caster can drink only from a golden bowl worth 100 gold pieces"
    ElseIf (Label1.Caption = 459) Then
        Text1.Text = "Caster can easily walk on ice while barefoot"
    ElseIf (Label1.Caption = 460) Then
        Text1.Text = "Caster can echolocate like a dolphin while naked and underwater"
    ElseIf (Label1.Caption = 461) Then
        Text1.Text = "Caster can endure normal fire one round per point of Constitution"
    ElseIf (Label1.Caption = 462) Then
        Text1.Text = "Caster can extend his legs to 150% of their normal length at will"
    ElseIf (Label1.Caption = 463) Then
        Text1.Text = "Caster can extend his legs to 2X their normal length at will"
    ElseIf (Label1.Caption = 464) Then
        Text1.Text = "Caster can handle red-hot metal with his bare hands"
    ElseIf (Label1.Caption = 465) Then
        Text1.Text = "Caster can hear what occurs at this location from up to 10 miles"
    ElseIf (Label1.Caption = 466) Then
        Text1.Text = "Caster can hear what’s going on in his home, wherever he is"
    ElseIf (Label1.Caption = 467) Then
        Text1.Text = "Caster can hold his breath for 3X his Wisdom score in rounds"
    ElseIf (Label1.Caption = 468) Then
        Text1.Text = "Caster can hurl a baseball-sized object beyond the horizon"
    ElseIf (Label1.Caption = 469) Then
        Text1.Text = "Caster can identify any kind of fungus on sight"
    ElseIf (Label1.Caption = 470) Then
        Text1.Text = "Caster can ignite twigs by sticking them in his mouth"
    ElseIf (Label1.Caption = 471) Then
        Text1.Text = "Caster can ignore any spell cast on him but is 80% likely to die"
    ElseIf (Label1.Caption = 472) Then
        Text1.Text = "Caster can induce ravenous hunger in others"
    ElseIf (Label1.Caption = 473) Then
        Text1.Text = "Caster can inflate his left hand like a balloon"
    ElseIf (Label1.Caption = 474) Then
        Text1.Text = "Caster can instantly count quantities of fewer than 1,000 items"
    ElseIf (Label1.Caption = 475) Then
        Text1.Text = "Caster can judge visible distances with amazing accuracy"
    ElseIf (Label1.Caption = 476) Then
        Text1.Text = "Caster can light candles simply by touching their wicks"
    ElseIf (Label1.Caption = 477) Then
        Text1.Text = "Caster can magically create edible but non-nourishing food"
    ElseIf (Label1.Caption = 478) Then
        Text1.Text = "Caster can make his ears resemble noses at will"
    ElseIf (Label1.Caption = 479) Then
        Text1.Text = "Caster can memorize spells 4x faster than is normally required"
    ElseIf (Label1.Caption = 480) Then
        Text1.Text = "Caster can move easily through running water less than waist-deep"
    ElseIf (Label1.Caption = 481) Then
        Text1.Text = "Caster can move in total silence for his Wisdom score in rounds"
    ElseIf (Label1.Caption = 482) Then
        Text1.Text = "Caster can move silently while holding a thumb in each nostril"
    ElseIf (Label1.Caption = 483) Then
        Text1.Text = "Caster can never again come within one mile of his home"
    ElseIf (Label1.Caption = 484) Then
        Text1.Text = "Caster can no longer use charged magic items"
    ElseIf (Label1.Caption = 485) Then
        Text1.Text = "Caster can only digest food that is spoiled or rotting"
    ElseIf (Label1.Caption = 486) Then
        Text1.Text = "Caster can only use electrical magic while standing in water"
    ElseIf (Label1.Caption = 487) Then
        Text1.Text = "Caster can only wear one shoe at a time"
    ElseIf (Label1.Caption = 488) Then
        Text1.Text = "Caster can open his mouth as wide as he is tall"
    ElseIf (Label1.Caption = 489) Then
        Text1.Text = "Caster can pass his right arm through up to six inches of wood"
    ElseIf (Label1.Caption = 490) Then
        Text1.Text = "Caster can reattach his own limbs if they’re severed"
    ElseIf (Label1.Caption = 491) Then
        Text1.Text = "Caster can recall his own birth with perfect clarity"
    ElseIf (Label1.Caption = 492) Then
        Text1.Text = "Caster can remove his tongue and replace it at will"
    ElseIf (Label1.Caption = 493) Then
        Text1.Text = "Caster can remove one eye and replace it at will"
    ElseIf (Label1.Caption = 494) Then
        Text1.Text = "Caster can remove or negate one curse"
    ElseIf (Label1.Caption = 495) Then
        Text1.Text = "Caster can resemble a decaying zombie at will"
    ElseIf (Label1.Caption = 496) Then
        Text1.Text = "Caster can retract his feet into his ankles at will"
    ElseIf (Label1.Caption = 497) Then
        Text1.Text = "Caster can retract his fingers into his palms at will"
    ElseIf (Label1.Caption = 498) Then
        Text1.Text = "Caster can retract his nose into his face at will"
    ElseIf (Label1.Caption = 499) Then
        Text1.Text = "Caster can scale walls like a monkey while unencumbered"
    ElseIf (Label1.Caption = 500) Then
        Text1.Text = "Caster can see in total darkness if he has a banana in his pocket"
    ElseIf (Label1.Caption = 501) Then
        Text1.Text = "Caster can see secret doors easily but can’t see normal doors"
    ElseIf (Label1.Caption = 502) Then
        Text1.Text = "Caster can see through fire"
    ElseIf (Label1.Caption = 503) Then
        Text1.Text = "Caster can see through his eyelids for up to 1d6 rounds at a time"
    ElseIf (Label1.Caption = 504) Then
        Text1.Text = "Caster can see through stone if he has a pebble in his mouth"
    ElseIf (Label1.Caption = 505) Then
        Text1.Text = "Caster can see underwater clearly while naked and wielding an axe"
    ElseIf (Label1.Caption = 506) Then
        Text1.Text = "Caster can seem to be infected with a particular disease at will"
    ElseIf (Label1.Caption = 507) Then
        Text1.Text = "Caster can seen in total darkness for 1d4 days"
    ElseIf (Label1.Caption = 508) Then
        Text1.Text = "Caster can sense intelligent weapons within 10 yards"
    ElseIf (Label1.Caption = 509) Then
        Text1.Text = "Caster can sense people who’ve been affected by Chaos Bursts"
    ElseIf (Label1.Caption = 510) Then
        Text1.Text = "Caster can speak but can’t engage in actual conversations"
    ElseIf (Label1.Caption = 511) Then
        Text1.Text = "Caster can speak in a whisper to anyone in his line of sight"
    ElseIf (Label1.Caption = 512) Then
        Text1.Text = "Caster can speak in any of 2d4 voices at will"
    ElseIf (Label1.Caption = 513) Then
        Text1.Text = "Caster can speak with ants but can only ask yes/no questions"
    ElseIf (Label1.Caption = 514) Then
        Text1.Text = "Caster can speak with carrion birds, but he smells like a corpse"
    ElseIf (Label1.Caption = 515) Then
        Text1.Text = "Caster can speak with carrion birds, but he’s permanently bald"
    ElseIf (Label1.Caption = 516) Then
        Text1.Text = "Caster can speak with domestic fowl, but he crows at sunrise"
    ElseIf (Label1.Caption = 517) Then
        Text1.Text = "Caster can speak with domestic fowl, but they tend to lie to him"
    ElseIf (Label1.Caption = 518) Then
        Text1.Text = "Caster can speak with honeybees while dancing like one of them"
    ElseIf (Label1.Caption = 519) Then
        Text1.Text = "Caster can speak with oysters while holding a pearl in his mouth"
    ElseIf (Label1.Caption = 520) Then
        Text1.Text = "Caster can speak with small fish, but only while underwater"
    ElseIf (Label1.Caption = 521) Then
        Text1.Text = "Caster can spot the strongest member of any group of five or more"
    ElseIf (Label1.Caption = 522) Then
        Text1.Text = "Caster can stretch his left arm 2X the length of his body"
    ElseIf (Label1.Caption = 523) Then
        Text1.Text = "Caster can subsist on bark for up to 1d4 days at a time"
    ElseIf (Label1.Caption = 524) Then
        Text1.Text = "Caster can Summon 1d10 rabbits, once per level per week"
    ElseIf (Label1.Caption = 525) Then
        Text1.Text = "Caster can Summon a powerful entity to answer one question"
    ElseIf (Label1.Caption = 526) Then
        Text1.Text = "Caster can Summon a powerful entity who will then try to kill him"
    ElseIf (Label1.Caption = 527) Then
        Text1.Text = "Caster can Summon but not control a powerful, malevolent entity"
    ElseIf (Label1.Caption = 528) Then
        Text1.Text = "Caster can Summon up to 1d10 pigeons per month"
    ElseIf (Label1.Caption = 529) Then
        Text1.Text = "Caster can survive at the bottom of the sea for 1d4 minutes"
    ElseIf (Label1.Caption = 530) Then
        Text1.Text = "Caster can survive in the depths of space, if he can get there"
    ElseIf (Label1.Caption = 531) Then
        Text1.Text = "Caster can survive one fall of up to twenty miles"
    ElseIf (Label1.Caption = 532) Then
        Text1.Text = "Caster can taste foods simply by touching them"
    ElseIf (Label1.Caption = 533) Then
        Text1.Text = "Caster can teleport 10 feet straight up, once per day"
    ElseIf (Label1.Caption = 534) Then
        Text1.Text = "Caster can teleport 10 times at will but loses a finger each time"
    ElseIf (Label1.Caption = 535) Then
        Text1.Text = "Caster can teleport at will but ages 1d100 years each time"
    ElseIf (Label1.Caption = 536) Then
        Text1.Text = "Caster can teleport at will but arrives unconscious for one hour"
    ElseIf (Label1.Caption = 537) Then
        Text1.Text = "Caster can teleport at will but can’t pick the destination"
    ElseIf (Label1.Caption = 537) Then
        Text1.Text = "Caster can teleport at will but can’t pick the destination"
    ElseIf (Label1.Caption = 538) Then
        Text1.Text = "Caster can teleport at will but doesn’t arrive for 1d12 months"
    ElseIf (Label1.Caption = 539) Then
        Text1.Text = "Caster can teleport at will but is 10% likely to arrive dead"
    ElseIf (Label1.Caption = 540) Then
        Text1.Text = "Caster can teleport at will but is paralyzed from the neck down"
    ElseIf (Label1.Caption = 541) Then
        Text1.Text = "Caster can teleport at will but loses 1d100 hit points each time"
    ElseIf (Label1.Caption = 542) Then
        Text1.Text = "Caster can teleport at will but only while naked and unencumbered"
    ElseIf (Label1.Caption = 543) Then
        Text1.Text = "Caster can teleport at will but shrinks by 50% per mile traveled"
    ElseIf (Label1.Caption = 544) Then
        Text1.Text = "Caster can teleport at will to this exact spot 2d6 times"
    ElseIf (Label1.Caption = 545) Then
        Text1.Text = "Caster can teleport into the nearest hollow tree, once"
    ElseIf (Label1.Caption = 546) Then
        Text1.Text = "Caster can teleport up to fifty feet once per day"
    ElseIf (Label1.Caption = 547) Then
        Text1.Text = "Caster can throw one baseball-sized item 2d6 days into the future"
    ElseIf (Label1.Caption = 548) Then
        Text1.Text = "Caster can throw one nearby person 1d10 rounds into the future"
    ElseIf (Label1.Caption = 549) Then
        Text1.Text = "Caster can throw one nearby person 1d4 days into the future"
    ElseIf (Label1.Caption = 550) Then
        Text1.Text = "Caster can transmute magically-created metal into wood"
    ElseIf (Label1.Caption = 551) Then
        Text1.Text = "Caster can travel in time but ages 1d10 years per round traveled"
    ElseIf (Label1.Caption = 552) Then
        Text1.Text = "Caster can turn 360° at the waist without harm"
    ElseIf (Label1.Caption = 553) Then
        Text1.Text = "Caster can turn ethereal at will but can’t revert for 3d8 days"
    ElseIf (Label1.Caption = 554) Then
        Text1.Text = "Caster can turn his arms to wood for up to 1d6 rounds per day"
    ElseIf (Label1.Caption = 555) Then
        Text1.Text = "Caster can turn his bones invisible at will"
    ElseIf (Label1.Caption = 556) Then
        Text1.Text = "Caster can turn his hands invisible at will 1d8 times per day"
    ElseIf (Label1.Caption = 557) Then
        Text1.Text = "Caster can turn his head completely around once per day"
    ElseIf (Label1.Caption = 558) Then
        Text1.Text = "Caster can turn into a cat but can’t resume his true form"
    ElseIf (Label1.Caption = 559) Then
        Text1.Text = "Caster can turn into a falcon but is only 30% likely to turn back"
    ElseIf (Label1.Caption = 560) Then
        Text1.Text = "Caster can turn into a small tree while he’s indoors"
    ElseIf (Label1.Caption = 561) Then
        Text1.Text = "Caster can turn into any kind of fish if no water is nearby"
    ElseIf (Label1.Caption = 562) Then
        Text1.Text = "Caster can turn invisible while he holds his breath"
    ElseIf (Label1.Caption = 563) Then
        Text1.Text = "Caster can turn invisible while naked and motionless"
    ElseIf (Label1.Caption = 564) Then
        Text1.Text = "Caster can walk on inclines of 45° or less as if they were flat"
    ElseIf (Label1.Caption = 565) Then
        Text1.Text = "Caster can withstand ocean depths while holding a bar of sodium"
    ElseIf (Label1.Caption = 566) Then
        Text1.Text = "Caster can, at will, appear to be the next person he touches"
    ElseIf (Label1.Caption = 567) Then
        Text1.Text = "Caster can’t attack anyone more than 20 feet away from him"
    ElseIf (Label1.Caption = 568) Then
        Text1.Text = "Caster can’t be beheaded"
    ElseIf (Label1.Caption = 569) Then
        Text1.Text = "Caster can’t be blinded or dazzled by sunlight"
    ElseIf (Label1.Caption = 570) Then
        Text1.Text = "Caster can’t be burned by magical fire for 1d4 hours"
    ElseIf (Label1.Caption = 571) Then
        Text1.Text = "Caster can’t be burned by steam or scalding water"
    ElseIf (Label1.Caption = 572) Then
        Text1.Text = "Caster can’t be Charmed by anyone of the opposite sex"
    ElseIf (Label1.Caption = 573) Then
        Text1.Text = "Caster can’t be crushed by any weight of stone"
    ElseIf (Label1.Caption = 574) Then
        Text1.Text = "Caster can’t be cut by any blade until he casts his next spell"
    ElseIf (Label1.Caption = 575) Then
        Text1.Text = "Caster can’t be cut by glass"
    ElseIf (Label1.Caption = 576) Then
        Text1.Text = "Caster can’t be cut by non-magical blades for 1d4 days"
    ElseIf (Label1.Caption = 577) Then
        Text1.Text = "Caster can’t be harmed by any member of the royal family"
    ElseIf (Label1.Caption = 578) Then
        Text1.Text = "Caster can’t be harmed by loud, non-magical sound"
    ElseIf (Label1.Caption = 579) Then
        Text1.Text = "Caster can’t be harmed by refined metals for 1d4 hours"
    ElseIf (Label1.Caption = 580) Then
        Text1.Text = "Caster can’t be harmed while he stands where he is right now"
    ElseIf (Label1.Caption = 581) Then
        Text1.Text = "Caster can’t be killed by anyone of his own race"
    ElseIf (Label1.Caption = 582) Then
        Text1.Text = "Caster can’t be overwhelmed by foul odors"
    ElseIf (Label1.Caption = 583) Then
        Text1.Text = "Caster can’t be seen through glass or ice"
    ElseIf (Label1.Caption = 584) Then
        Text1.Text = "Caster can’t be strangled"
    ElseIf (Label1.Caption = 585) Then
        Text1.Text = "Caster can’t breathe for 4d6 rounds"
    ElseIf (Label1.Caption = 586) Then
        Text1.Text = "Caster can’t bring his left hand within 18 inches of his head"
    ElseIf (Label1.Caption = 587) Then
        Text1.Text = "Caster can’t carry anything larger than his own head"
    ElseIf (Label1.Caption = 588) Then
        Text1.Text = "Caster can’t carry anything made entirely of metal"
    ElseIf (Label1.Caption = 589) Then
        Text1.Text = "Caster can’t carry refined metal in a wooded environment"
    ElseIf (Label1.Caption = 590) Then
        Text1.Text = "Caster can’t cast any spells he now has memorized for 1d8 days"
    ElseIf (Label1.Caption = 591) Then
        Text1.Text = "Caster can’t cast fire-based magic while in the rain"
    ElseIf (Label1.Caption = 592) Then
        Text1.Text = "Caster can’t cast fire-based spells in a wooded environment"
    ElseIf (Label1.Caption = 593) Then
        Text1.Text = "Caster can’t cast force-based spells (Wall of Force, etc.)"
    ElseIf (Label1.Caption = 594) Then
        Text1.Text = "Caster can’t cast magic on anyone not wearing armor"
    ElseIf (Label1.Caption = 595) Then
        Text1.Text = "Caster can’t cast magic on anyone while they’re eating"
    ElseIf (Label1.Caption = 596) Then
        Text1.Text = "Caster can’t cast magic unless he’s within sight of a tree"
    ElseIf (Label1.Caption = 597) Then
        Text1.Text = "Caster can’t cast magic upon himself for 1d4 weeks"
    ElseIf (Label1.Caption = 598) Then
        Text1.Text = "Caster can’t create magical walls or barriers"
    ElseIf (Label1.Caption = 599) Then
        Text1.Text = "Caster can’t create normal or magical fire for 1d4 days"
    ElseIf (Label1.Caption = 600) Then
        Text1.Text = "Caster can’t create permanent magical objects or effects"
    ElseIf (Label1.Caption = 601) Then
        Text1.Text = "Caster can’t cross moving water while brandishing a weapon"
    ElseIf (Label1.Caption = 602) Then
        Text1.Text = "Caster can’t cross moving water while carrying his spellbook"
    ElseIf (Label1.Caption = 603) Then
        Text1.Text = "Caster can’t cross moving water while wearing clothes"
    ElseIf (Label1.Caption = 604) Then
        Text1.Text = "Caster can’t cross moving water while wearing magical rings"
    ElseIf (Label1.Caption = 605) Then
        Text1.Text = "Caster can’t cross moving water without assistance"
    ElseIf (Label1.Caption = 606) Then
        Text1.Text = "Caster can’t determine when he’s hungry or thirsty"
    ElseIf (Label1.Caption = 607) Then
        Text1.Text = "Caster can’t eat any cooked meat"
    ElseIf (Label1.Caption = 608) Then
        Text1.Text = "Caster can’t eat any food that doesn’t contain a handful of soil"
    ElseIf (Label1.Caption = 609) Then
        Text1.Text = "Caster can’t eat any food that he himself didn’t prepare"
    ElseIf (Label1.Caption = 610) Then
        Text1.Text = "Caster can’t eat any salted or cured meat"
    Else
        Text1.Text = "Roll result not yet programmed"
    End If
End Sub
Private Function RandomNumBetween(ByVal LowerLimit As Long, ByVal UpperLimit As Long) As Long
  ' This function returns a pseudo-random number between
  ' the specified limits (inclusive).
  RandomNumBetween = Rnd * (UpperLimit - LowerLimit) + LowerLimit
End Function
